# Generated by Django 4.1.13 on 2024-11-21 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_topic_userprogress_word_delete_vocabword"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mistake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField()),
                ("mistakes_count", models.IntegerField(default=0)),
                (
                    "user_progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mistakes",
                        to="api.userprogress",
                    ),
                ),
            ],
            options={
                "unique_together": {("user_progress", "level")},
            },
        ),
        migrations.CreateModel(
            name="ExperimentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "presentation_style",
                    models.CharField(
                        choices=[("B", "Basic"), ("I", "Image"), ("S", "Sentence")],
                        max_length=1,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiment_groups",
                        to="api.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiment_groups",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "topic")},
            },
        ),
    ]
