# Generated by Django 4.1.13 on 2024-12-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_mistake_date_taken_mistake_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="examresult",
            name="duration",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
