# Generated by Django 4.1.13 on 2024-12-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_examresult_duration_alter_examresult_score"),
    ]

    operations = [
        migrations.RenameField(
            model_name="examanswer",
            old_name="answer_text",
            new_name="answer",
        ),
        migrations.AddField(
            model_name="examanswer",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
