# Generated by Django 4.1.13 on 2024-12-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_rename_answer_text_examanswer_answer_examanswer_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="word",
            name="image",
        ),
    ]
